
import { SelectProps } from 'antd';

export const options: SelectProps['options'] = [
  { label: 'Almonds', value: 'almonds', desc: 'Almonds' },
  { label: 'Chicken broth', value: 'chicken_broth', desc: 'Chicken broth' },
  { label: 'Cheese', value: 'cheese', desc: 'Cheese' },
  { label: 'Buttermilk', value: 'buttermilk', desc: 'Buttermilk' },
  { label: 'Popcorn', value: 'popcorn', desc: 'Popcorn' },
  { label: 'Romaine lettuce', value: 'romaine_lettuce', desc: 'Romaine lettuce' },
  { label: 'Grilled chicken', value: 'grilled_chicken', desc: 'Grilled chicken' },
  { label: 'Strawberries', value: 'strawberries', desc: 'Strawberries' },
  { label: 'Potatoes', value: 'potatoes', desc: 'Potatoes' },
  { label: 'Yogurt (milk, cultures)', value: 'yogurt_milk_cultures', desc: 'Yogurt (milk, cultures)' },
  { label: 'Tomatoes', value: 'tomatoes', desc: 'Tomatoes' },
  { label: 'Mixed berries', value: 'mixed_berries', desc: 'Mixed berries' },
  { label: 'Chicken', value: 'chicken', desc: 'Chicken' },
  { label: 'Pesto sauce', value: 'pesto_sauce', desc: 'Pesto sauce' },
  { label: 'Beef', value: 'beef', desc: 'Beef' },
  { label: 'Bananas', value: 'bananas', desc: 'Bananas' },
  { label: 'Watermelon', value: 'watermelon', desc: 'Watermelon' },
  { label: 'Mango', value: 'mango', desc: 'Mango' },
  { label: 'Cucumbers', value: 'cucumbers', desc: 'Cucumbers' },
  { label: 'Butternut squash', value: 'butternut_squash', desc: 'Butternut squash' },
  { label: 'Pasta', value: 'pasta', desc: 'Pasta' },
  { label: 'Lamb', value: 'lamb', desc: 'Lamb' },
  { label: 'Mushrooms', value: 'mushrooms', desc: 'Mushrooms' },
  { label: 'Greek yogurt', value: 'greek_yogurt', desc: 'Greek yogurt' },
  { label: 'Eggplant', value: 'eggplant', desc: 'Eggplant' },
  { label: 'Pizza dough', value: 'pizza_dough', desc: 'Pizza dough' },
  { label: 'Spinach', value: 'spinach', desc: 'Spinach' },
  { label: 'Chocolate', value: 'chocolate', desc: 'Chocolate' },
  { label: 'Portobello mushrooms', value: 'portobello_mushrooms', desc: 'Portobello mushrooms' },
  { label: 'Pumpkin', value: 'pumpkin', desc: 'Pumpkin' },
  { label: 'Berries', value: 'berries', desc: 'Berries' },
  { label: 'Paneer', value: 'paneer', desc: 'Paneer' },
  { label: 'Lentils', value: 'lentils', desc: 'Lentils' },
  { label: 'Cottage cheese', value: 'cottage_cheese', desc: 'Cottage cheese' },
  { label: 'Milk solids', value: 'milk_solids', desc: 'Milk solids' },
  { label: 'Lentil dumplings', value: 'lentil_dumplings', desc: 'Lentil dumplings' },
  { label: 'Milk', value: 'milk', desc: 'Milk' },
  { label: 'Rice', value: 'rice', desc: 'Rice' },
  { label: 'Chicken breast', value: 'chicken_breast', desc: 'Chicken breast' },
  { label: 'Bacon', value: 'bacon', desc: 'Bacon' },
  { label: 'Sweet potatoes', value: 'sweet_potatoes', desc: 'Sweet potatoes' },
  { label: 'Brie cheese', value: 'brie_cheese', desc: 'Brie cheese' },
  { label: 'Onions', value: 'onions', desc: 'Onions' },
  { label: 'Lamb/Chicken', value: 'lamb_chicken', desc: 'Lamb/Chicken' },
  { label: 'Eggs', value: 'eggs', desc: 'Eggs' },
  { label: 'Fish fillets', value: 'fish_fillets', desc: 'Fish fillets' },
  { label: 'Salmon fillet', value: 'salmon_fillet', desc: 'Salmon fillet' },
  { label: 'Salmon', value: 'salmon', desc: 'Salmon' },
  { label: 'Fish', value: 'fish', desc: 'Fish' },
  { label: 'Cod', value: 'cod', desc: 'Cod' },
  { label: 'Tuna', value: 'tuna', desc: 'Tuna' },
  { label: 'Fish (salmon, tuna)', value: 'fish_salmon_tuna', desc: 'Fish (salmon, tuna)' },
  { label: 'Sushi rice', value: 'sushi_rice', desc: 'Sushi rice' },
  { label: 'Sugar', value: 'sugar', desc: 'Sugar' },
  { label: 'Apples', value: 'apples', desc: 'Apples' },
  { label: 'Oranges', value: 'oranges', desc: 'Oranges' },
  { label: 'Cucumber', value: 'cucumber', desc: 'Cucumber' },
  { label: 'Ground beef', value: 'ground_beef', desc: 'Ground beef' },
  { label: 'Pork ribs', value: 'pork_ribs', desc: 'Pork ribs' },
  { label: 'Quinoa', value: 'quinoa', desc: 'Quinoa' },
  { label: 'Mixed vegetables', value: 'mixed_vegetables', desc: 'Mixed vegetables' },
  { label: 'Lemon juice', value: 'lemon_juice', desc: 'Lemon juice' },
  { label: 'Vegetables', value: 'vegetables', desc: 'Vegetables' },
  { label: 'Avocado', value: 'avocado', desc: 'Avocado' },
  { label: 'Black beans', value: 'black_beans', desc: 'Black beans' },
  { label: 'Mixed fruits', value: 'mixed_fruits', desc: 'Mixed fruits' },
  { label: 'Sausage', value: 'sausage', desc: 'Sausage' },
  { label: 'Bell peppers', value: 'bell_peppers', desc: 'Bell peppers' },
  { label: 'Cabbage', value: 'cabbage', desc: 'Cabbage' },
  { label: 'Zucchini', value: 'zucchini', desc: 'Zucchini' },
  { label: 'Chicken wings', value: 'chicken_wings', desc: 'Chicken wings' },
  { label: 'Tofu', value: 'tofu', desc: 'Tofu' },
  { label: 'Brussels sprouts', value: 'brussels_sprouts', desc: 'Brussels sprouts' },
  { label: 'Carrots', value: 'carrots', desc: 'Carrots' },
  { label: 'Chickpeas', value: 'chickpeas', desc: 'Chickpeas' },
  { label: 'Potato', value: 'potato', desc: 'Potato' },
  { label: 'Semolina', value: 'semolina', desc: 'Semolina' },
  { label: 'Kidney beans', value: 'kidney_beans', desc: 'Kidney beans' },
  { label: 'Fermented batter', value: 'fermented_batter', desc: 'Fermented batter' },
  { label: 'Basmati rice', value: 'basmati_rice', desc: 'Basmati rice' },
  { label: 'Cauliflower', value: 'cauliflower', desc: 'Cauliflower' },
  { label: 'Mutton', value: 'mutton', desc: 'Mutton' },
  { label: 'Oats', value: 'oats', desc: 'Oats' },
  { label: 'Peanuts', value: 'peanuts', desc: 'Peanuts' },
  { label: 'Shrimp', value: 'shrimp', desc: 'Shrimp' },
  { label: 'Prawns', value: 'prawns', desc: 'Prawns' },
  { label: 'Lobster', value: 'lobster', desc: 'Lobster' },
  { label: 'Soybeans', value: 'soybeans', desc: 'Soybeans' },
  { label: 'Miso paste', value: 'miso_paste', desc: 'Miso paste' },
  { label: 'Wheat flour', value: 'wheat_flour', desc: 'Wheat flour' },
  { label: 'Flour', value: 'flour', desc: 'Flour' },
  { label: 'Blueberries', value: 'blueberries', desc: 'Blueberries' },
  { label: 'Arborio rice', value: 'arborio_rice', desc: 'Arborio rice' },
  { label: 'Pineapple', value: 'pineapple', desc: 'Pineapple' },
  { label: 'Bread', value: 'bread', desc: 'Bread' },
  { label: 'Lime juice', value: 'lime_juice', desc: 'Lime juice' },
  { label: 'Cream cheese', value: 'cream_cheese', desc: 'Cream cheese' },
  { label: 'Graham crackers', value: 'graham_crackers', desc: 'Graham crackers' },
  { label: 'Ladyfingers', value: 'ladyfingers', desc: 'Ladyfingers' },
  { label: 'Dough', value: 'dough', desc: 'Dough' },
  { label: 'Pecans', value: 'pecans', desc: 'Pecans' },
];
